/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as boxV2Sol from "./BoxV2.sol";
export type { boxV2Sol };
import type * as proxy from "./proxy";
export type { proxy };
export type { Box } from "./Box";
