/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as proxy from "./proxy";
export { Box__factory } from "./Box__factory";
export { BoxV2__factory } from "./BoxV2__factory";
