/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as boxV2Sol from "./BoxV2.sol";
export * as proxy from "./proxy";
export { Box__factory } from "./Box__factory";
